[package]
name = "rust-messenger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tokio"]

[dependencies]
libc = "0.2.153"
tokio = { version = "*", optional = true, features = [
    "rt-multi-thread",
    "sync",
    "macros",
] }

[dev-dependencies]
bincode = "1.3.3"
serde = { version = "1.0.197", features = ["derive"] }
