mod config;
mod handlers;
mod messages;

// This example carries protobuf messages — the same types a connect-rust
// service would use, generated by the buffa runtime — over the in-process
// CircularBus instead of a socket:
//
//   Client -> GetAccountRequest -> AccountService
//   AccountService -> GetAccountResponse -> Client
//
// Senders write OWNED messages (serialized by buffa). Receivers are routed
// the borrowed VIEW types: the route names `...View`, so each handler decodes
// the slot in place with buffa's zero-copy `decode_view` — string fields
// borrow straight from the bus buffer with no allocation.

rust_messenger::Messenger! {
    config::Config,
    Frontend:
        handlers: [
            client: handlers::Client,
        ]
        routes: [
            handlers::AccountService, messages::GetAccountResponseView: [ client ],
        ]
    Backend:
        handlers: [
            account_service: handlers::AccountService,
        ]
        routes: [
            handlers::Client, messages::GetAccountRequestView: [ account_service ],
        ]
}

pub fn main() {
    use rust_messenger::traits::core::Reader;

    let config = config::Config {};
    let bus = rust_messenger::message_bus::atomic_circular_bus::CircularBus::new(&config);
    let messenger = Messenger::new(bus.clone());
    let handles = messenger.run(&config);

    // Watch the bus for the response instead of guessing a sleep duration, so
    // the example shuts down deterministically once the round trip completes.
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
    let mut position = 0;
    'wait: while std::time::Instant::now() < deadline {
        while let Some((header, _)) = bus.read(position) {
            position += header.slot_len();
            if header.message_id == u16::from(messages::MessageId::GetAccountResponse) {
                break 'wait;
            }
        }
        std::thread::yield_now();
    }

    // Brief grace period so the client routes and prints the response before
    // the stop flag ends the worker loops.
    std::thread::sleep(std::time::Duration::from_millis(10));
    messenger.stop();
    handles.join();
}
